// AUTH actions
export const AUTH_INIT = 'AUTH_INIT'
export const AUTH_GET_USER = 'AUTH_GET_USER'
export const AUTH_SET_STATE = 'AUTH_SET_STATE'
export const AUTH_SIGN_UP = 'AUTH_SIGN_UP'
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN'
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT'
export const AUTH_FORGOT_PASSWORD = 'AUTH_FORGOT_PASSWORD'
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD'
export const AUTH_COMPLETE_NEW_PASSWORD = 'AUTH_COMPLETE_NEW_PASSWORD'
export const AUTH_CHANGE_SUCCESSFUL = 'AUTH_CHANGE_SUCCESSFUL'


export const USER_INIT = "USER_INIT"
export const USER_SET_STATE = "USER_SET_STATE"
export const USER_S3_UPLOAD_TOKEN_REQUESTED = 'USER_S3_UPLOAD_TOKEN_REQUESTED'
export const USER_S3_UPLOAD_TOKEN_REQUEST_SENT = 'USER_S3_UPLOAD_TOKEN_REQUEST_SENT'
export const USER_S3_UPLOAD_TOKEN_REQUEST_FAILED = 'USER_S3_UPLOAD_TOKEN_REQUEST_FAILED'


export const PROJECT_INIT = "PROJECT_INIT"
export const PROJECT_SET_STATE = "PROJECT_SET_STATE"
export const PROJECT_PROJECT_CHOSEN = "PROJECT_PROJECT_CHOSEN"
export const PROJECT_GET_ACCESSIBLE_PROJECTS_REQUESTED = "PROJECT_GET_ACCESSIBLE_PROJECTS_REQUESTED"
export const PROJECT_GET_ACCESSIBLE_PROJECTS_REQUEST_SENT = "PROJECT_GET_ACCESSIBLE_PROJECTS_REQUEST_SENT"
export const PROJECT_GET_ACCESSIBLE_PROJECTS_REQUEST_FAILED = "PROJECT_GET_ACCESSIBLE_PROJECTS_REQUEST_FAILED"

export const PROJECT_CREATE_PROJECT_REQUESTED = 'PROJECT_CREATE_PROJECT_REQUESTED'
export const PROJECT_CREATE_PROJECT_REQUEST_SENT = 'PROJECT_CREATE_PROJECT_REQUEST_SENT'
export const PROJECT_CREATE_PROJECT_REQUEST_FAILED = 'PROJECT_CREATE_PROJECT_REQUEST_FAILED'
