// AUTH actions
export const AUTH_INIT = 'AUTH_INIT'
export const AUTH_GET_USER = 'AUTH_GET_USER'
export const AUTH_SET_STATE = 'AUTH_SET_STATE'
export const AUTH_SIGN_UP = 'AUTH_SIGN_UP'
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN'
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT'
export const AUTH_FORGOT_PASSWORD = 'AUTH_FORGOT_PASSWORD'
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD'
export const AUTH_COMPLETE_NEW_PASSWORD = 'AUTH_COMPLETE_NEW_PASSWORD'
export const AUTH_CHANGE_SUCCESSFUL = 'AUTH_CHANGE_SUCCESSFUL'


export const USER_INIT = "USER_INIT"
export const USER_SET_STATE = "USER_SET_STATE"
export const USER_S3_UPLOAD_TOKEN_REQUESTED = 'USER_S3_UPLOAD_TOKEN_REQUESTED'
export const USER_S3_UPLOAD_TOKEN_REQUEST_SENT = 'USER_S3_UPLOAD_TOKEN_REQUEST_SENT'
export const USER_S3_UPLOAD_TOKEN_REQUEST_FAILED = 'USER_S3_UPLOAD_TOKEN_REQUEST_FAILED'


export const PROJECT_INIT = "PROJECT_INIT"
export const PROJECT_ID_CHANGED = "PROJECT_ID_CHANGED"
export const PROJECT_SET_STATE = "PROJECT_SET_STATE"
export const PROJECT_PROJECT_CHOSEN = "PROJECT_PROJECT_CHOSEN"
export const PROJECT_LOAD_DATA_TO_FORM = "PROJECT_LOAD_DATA_TO_FORM"
export const PROJECT_GET_ACCESSIBLE_PROJECTS_REQUESTED = "PROJECT_GET_ACCESSIBLE_PROJECTS_REQUESTED"
export const PROJECT_GET_ACCESSIBLE_PROJECTS_REQUEST_SENT = "PROJECT_GET_ACCESSIBLE_PROJECTS_REQUEST_SENT"
export const PROJECT_GET_ACCESSIBLE_PROJECTS_REQUEST_FAILED = "PROJECT_GET_ACCESSIBLE_PROJECTS_REQUEST_FAILED"

export const PROJECT_CREATE_PROJECT_REQUESTED = 'PROJECT_CREATE_PROJECT_REQUESTED'
export const PROJECT_CREATE_PROJECT_REQUEST_SENT = 'PROJECT_CREATE_PROJECT_REQUEST_SENT'
export const PROJECT_CREATE_PROJECT_REQUEST_FAILED = 'PROJECT_CREATE_PROJECT_REQUEST_FAILED'

export const PROJECT_GET_CURRENT_MEMBERS_REQUESTED = 'PROJECT_GET_CURRENT_MEMBERS_REQUESTED'
export const PROJECT_GET_CURRENT_MEMBERS_REQUEST_SENT = 'PROJECT_GET_CURRENT_MEMBERS_REQUEST_SENT'
export const PROJECT_GET_CURRENT_MEMBERS_REQUEST_FAILED = 'PROJECT_GET_CURRENT_MEMBERS_REQUEST_FAILED'




export const MEMBER_INIT = "MEMBER_INIT"
export const MEMBER_SET_STATE = "MEMBER_SET_STATE"
export const MEMBER_ADD_MEMBER_REQUESTED = 'MEMBER_ADD_MEMBER_REQUESTED'
export const MEMBER_ADD_MEMBER_REQUEST_SENT = 'MEMBER_ADD_MEMBER_REQUEST_SENT'
export const MEMBER_ADD_MEMBER_REQUEST_FAILED = 'MEMBER_ADD_MEMBER_REQUEST_FAILED'

export const MEMBER_REMOVE_MEMBER_REQUESTED = 'MEMBER_REMOVE_MEMBER_REQUESTED'
export const MEMBER_REMOVE_MEMBER_REQUEST_SENT = 'MEMBER_REMOVE_MEMBER_REQUEST_SENT'
export const MEMBER_REMOVE_MEMBER_REQUEST_FAILED = 'MEMBER_REMOVE_MEMBER_REQUEST_FAILED'



export const PAGE_SET_STATE = "PAGE_SET_STATE"

export const PAGE_GET_CONTENT_INCEPTION_REQUESTED = 'PAGE_GET_CONTENT_INCEPTION_REQUESTED'
export const PAGE_GET_CONTENT_INCEPTION_REQUEST_SENT = 'PAGE_GET_CONTENT_INCEPTION_REQUEST_SENT'
export const PAGE_GET_CONTENT_INCEPTION_REQUEST_FAILED = 'PAGE_GET_CONTENT_INCEPTION_REQUEST_FAILED'
export const PAGE_INCEPTION_SET_STATE = 'PAGE_INCEPTION_SET_STATE'

export const PAGE_GET_CONTENT_FEASIBILITY_REQUESTED = 'PAGE_GET_CONTENT_FEASIBILITY_REQUESTED'
export const PAGE_GET_CONTENT_FEASIBILITY_REQUEST_SENT = 'PAGE_GET_CONTENT_FEASIBILITY_REQUEST_SENT'
export const PAGE_GET_CONTENT_FEASIBILITY_REQUEST_FAILED = 'PAGE_GET_CONTENT_FEASIBILITY_REQUEST_FAILED'
export const PAGE_FEASIBILITY_SET_STATE = 'PAGE_FEASIBILITY_SET_STATE'

export const PAGE_GET_CONTENT_DESIGN_REQUESTED = 'PAGE_GET_CONTENT_DESIGN_REQUESTED'
export const PAGE_GET_CONTENT_DESIGN_REQUEST_SENT = 'PAGE_GET_CONTENT_DESIGN_REQUEST_SENT'
export const PAGE_GET_CONTENT_DESIGN_REQUEST_FAILED = 'PAGE_GET_CONTENT_DESIGN_REQUEST_FAILED'
export const PAGE_DESIGN_SET_STATE = 'PAGE_DESIGN_SET_STATE'

export const PAGE_GET_CONTENT_TENDER_REQUESTED = 'PAGE_GET_CONTENT_TENDER_REQUESTED'
export const PAGE_GET_CONTENT_TENDER_REQUEST_SENT = 'PAGE_GET_CONTENT_TENDER_REQUEST_SENT'
export const PAGE_GET_CONTENT_TENDER_REQUEST_FAILED = 'PAGE_GET_CONTENT_TENDER_REQUEST_FAILED'
export const PAGE_TENDER_SET_STATE = 'PAGE_TENDER_SET_STATE'

export const PAGE_GET_CONTENT_CONSTRUCTION_REQUESTED = 'PAGE_GET_CONTENT_CONSTRUCTION_REQUESTED'
export const PAGE_GET_CONTENT_CONSTRUCTION_REQUEST_SENT = 'PAGE_GET_CONTENT_CONSTRUCTION_REQUEST_SENT'
export const PAGE_GET_CONTENT_CONSTRUCTION_REQUEST_FAILED = 'PAGE_GET_CONTENT_CONSTRUCTION_REQUEST_FAILED'
export const PAGE_CONSTRUCTION_SET_STATE = 'PAGE_CONSTRUCTION_SET_STATE'

export const PAGE_GET_CONTENT_HANDOVER_REQUESTED = 'PAGE_GET_CONTENT_HANDOVER_REQUESTED'
export const PAGE_GET_CONTENT_HANDOVER_REQUEST_SENT = 'PAGE_GET_CONTENT_HANDOVER_REQUEST_SENT'
export const PAGE_GET_CONTENT_HANDOVER_REQUEST_FAILED = 'PAGE_GET_CONTENT_HANDOVER_REQUEST_FAILED'
export const PAGE_HANDOVER_SET_STATE = 'PAGE_HANDOVER_SET_STATE'

export const PAGE_GET_CONTENT_OCCUPATION_REQUESTED = 'PAGE_GET_CONTENT_OCCUPATION_REQUESTED'
export const PAGE_GET_CONTENT_OCCUPATION_REQUEST_SENT = 'PAGE_GET_CONTENT_OCCUPATION_REQUEST_SENT'
export const PAGE_GET_CONTENT_OCCUPATION_REQUEST_FAILED = 'PAGE_GET_CONTENT_OCCUPATION_REQUEST_FAILED'
export const PAGE_OCCUPATION_SET_STATE = 'PAGE_OCCUPATION_SET_STATE'

export const PAGE_GET_CONTENT_REFURBISHMENT_REQUESTED = 'PAGE_GET_CONTENT_REFURBISHMENT_REQUESTED'
export const PAGE_GET_CONTENT_REFURBISHMENT_REQUEST_SENT = 'PAGE_GET_CONTENT_REFURBISHMENT_REQUEST_SENT'
export const PAGE_GET_CONTENT_REFURBISHMENT_REQUEST_FAILED = 'PAGE_GET_CONTENT_REFURBISHMENT_REQUEST_FAILED'
export const PAGE_REFURBISHMENT_SET_STATE = 'PAGE_REFURBISHMENT_SET_STATE'
