export const QUIESCENT = 'QUIESCENT'

export const UPLOADING_NEW_FILE_TO_SERVER = 'UPLOADING_NEW_FILE_TO_SERVER'
export const UPLOADING_NEW_FILE_TO_SERVER_FAILED = 'UPLOADING_NEW_FILE_TO_SERVER_FAILED'
export const UPLOADING_NEW_FILE_TO_SERVER_SUCCESS = 'UPLOADING_NEW_FILE_TO_SERVER_SUCCESS'

export const UPDATING_METADATA_ON_SERVER = 'UPDATING_METADATA_ON_SERVER'
export const UPDATING_METADATA_ON_SERVER_FAILED = 'UPDATING_METADATA_ON_SERVER_FAILED'
export const UPDATING_METADATA_ON_SERVER_SUCCESS = 'UPDATING_METADATA_ON_SERVER_SUCCESS'

export const CHECKING_EXISTING_FILE_EXISTS_ON_SERVER = 'CHECKING_EXISTING_FILE_EXISTS_ON_SERVER'
export const DOWNLOADING_EXISTING_FILE_FROM_SERVER = 'DOWNLOADING_EXISTING_FILE_FROM_SERVER'
export const DOWNLOADING_EXISTING_FILE_FROM_SERVER_FAILED = 'DOWNLOADING_EXISTING_FILE_FROM_SERVER_FAILED'
export const DOWNLOADING_EXISTING_FILE_FROM_SERVER_SUCCESS = 'DOWNLOADING_EXISTING_FILE_FROM_SERVER_SUCCESS'

export const CHECKING_S3_TOKEN_AVAILABILITY = 'CHECKING_S3_TOKEN_AVAILABILITY'
export const NO_S3_TOKEN_AVAILABLE = 'NO_S3_TOKEN_AVAILABLE'
export const S3_TOKEN_NOW_AVAILABLE = 'S3_TOKEN_NOW_AVAILABLE'

export const GIT_TEXT_WRITER_OPEN = 'GIT_TEXT_WRITER_OPEN'
export const GIT_TEXT_COMPARER_OPEN = 'GIT_TEXT_COMPARER_OPEN'
export const SHOW_COMMIT_DIALOGUE_BOX = 'SHOW_COMMIT_DIALOGUE_BOX'
