export const NO_PROJECT_SELECTED = 'NO_PROJECT_SELECTED'
export const QUIESCENT = 'QUIESCENT'
export const LOADING = 'LOADING'
export const ERROR_NO_PROCORE_ACCESS = 'ERROR_NO_PROCORE_ACCESS'

export const SHOW_NEW_MEMBERS_SETTINGS = 'SHOW_NEW_MEMBERS_SETTINGS'

export const ADDING_MEMBERS_TO_PROJECT = 'ADDING_MEMBERS_TO_PROJECT'
export const ADDING_MEMBERS_TO_PROJECT_FAILED = 'ADDING_MEMBERS_TO_PROJECT_FAILED'

export const FETCHING_CURRENT_PROJECT_MEMBERS = 'FETCHING_CURRENT_PROJECT_MEMBERS'
export const FETCHING_CURRENT_PROJECT_MEMBERS_FAILED = 'FETCHING_CURRENT_PROJECT_MEMBERS_FAILED'
