export const NO_PROJECT_SELECTED = 'NO_PROJECT_SELECTED'
export const QUIESCENT = 'QUIESCENT'

export const SHOW_NEW_MEMBER_SETTINGS = 'SHOW_NEW_MEMBER_SETTINGS'

export const ADDING_MEMBER_TO_PROJECT = 'ADDING_MEMBER_TO_PROJECT'
export const ADDING_MEMBER_TO_PROJECT_FAILED = 'ADDING_MEMBER_TO_PROJECT_FAILED'

export const FETCHING_CURRENT_PROJECT_MEMBERS = 'FETCHING_CURRENT_PROJECT_MEMBERS'
export const FETCHING_CURRENT_PROJECT_MEMBERS_FAILED = 'FETCHING_CURRENT_PROJECT_MEMBERS_FAILED'
