export const QUIESCENT = 'QUIESCENT'
export const LOADING = 'LOADING'
export const UPLOAD_IN_PROGESS = 'UPLOAD_IN_PROGESS'
export const ERROR_WHEN_LOADING = 'ERROR_WHEN_LOADING'

export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS'
export const PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED'

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'

export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED'
