export const DEFAULTPAGE = ""
export const DEFAULTLOGGEDINPAGE = "/Project"
export const PROJECTDETAILSPAGE = "/Project"
export const SIGNINPAGE = "/SignIn"
export const SIGNUPPAGE = "/SignUp"
export const MEMBERPAGE = "/Team"
