export const DEFAULTPAGE = ""
export const DEFAULTLOGGEDINPAGE = "/Inception"
//export const DEFAULTLOGGEDINPAGE = "/TestPage"
export const SIGNINPAGE = "/SignIn"
export const SIGNUPPAGE = "/SignUp"
export const MEMBERPAGE = "/Team"
